[package]
name = "ia"
version = "0.1.2"
authors = ["losfair <zhy20000919@hotmail.com>"]
description = "Ice application API library"
license = "MIT"
repository = "https://github.com/losfair/IceCore"

[dependencies]
futures = "0.1"
cwa = "0.1"
