language: rust
rust:
  - nightly
script:
  - PATH=/usr/lib/llvm-6.0/bin:$PATH cargo build --release --verbose
  - PATH=/usr/lib/llvm-6.0/bin:$PATH cargo test --release --verbose
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - llvm-6.0
            - llvm-6.0-dev
